# Generated by Django 5.2.7 on 2025-11-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('can_manage_crud', 'Puede crear, editar, y listar productos y modelos relacionados (Gestión/Admin)'), ('can_delete_permanently', 'Puede eliminar productos y modelos relacionados permanentemente (Solo Admin)'), ('can_view_raw_reports', 'Puede ver reportes SQL RAW (Gestión/Admin)')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
