# Generated by Django 5.2.7 on 2025-11-04 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('can_view_raw_reports', 'Puede ver reportes SQL RAW (Gestión/Admin)')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='usuarios_favoritos',
            field=models.ManyToManyField(blank=True, related_name='productos_favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que lo tienen como favorito'),
        ),
    ]
