# Generated by Django 5.2.7 on 2025-11-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_options_producto_usuarios_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción Detallada'),
            preserve_default=False,
        ),
    ]
