# Generated by Django 5.2.7 on 2025-11-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='producto.categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(related_name='productos_asociados', to='producto.etiqueta', verbose_name='Etiquetas'),
        ),
    ]
