# Generated by Django 5.2.7 on 2025-11-10 17:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_categoria_alter_producto_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El peso debe ser mayor a 0.00 kg. Ingrese un valor positivo.')], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
